services:
  - type: web
    name: aaronfrom215-gaming-news
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
